package by.bsuir.stock.controller;

public enum Commands {


    ADD_CARGO("ADD_CARGO"),
    DELETE_CARGO("DELETE_CARGO"),
    UPDATE_CARGO("UPDATE_CARGO"),
    GET_CARGO("GET_CARGO"),
    GET_CARGO_LIST("GET_CARGO_LIST"),
    GET_CARGO_LIST_BY_STOCK("GET_CARGO_LIST_BY_STOCK"),
    ADD_CARGOS("ADD_CARGOS"),
    UPDATE_CARGOS("UPDATE_CARGOS"),

    ADD_USER("ADD_USER"),
    DELETE_USER("DELETE_USER"),
    UPDATE_USER("UPDATE_USER"),
    GET_USER("GET_USER"),
    GET_USER_LIST("GET_USER_LIST"),
    AUTORIZATION_USER("AUTORIZATION_USER"),

    ADD_CARGO_IN_INVOICE("ADD_CARGO_IN_INVOICE"),

    ADD_INVOICE("ADD_INVOICE"),
    DELETE_INVOICE("DELETE_INVOICE"),
    UPDATE_INVOICE("UPDATE_INVOICE"),
    GET_INVOICE("GET_INVOICE"),
    GET_INVOICE_LIST("GET_INVOICE_LIST"),
    GET_INVOICE_BY_USER_ID(""),

    ADD_STOCK("ADD_STOCK"),
    DELETE_STOCK("DELETE_STOCK"),
    DELETE_STOCKS("DELETE_STOCKS"),
    UPDATE_STOCK("UPDATE_STOCK"),
    GET_STOCK("GET_STOCK"),
    GET_STOCK_LIST("GET_STOCK_LIST");


    private String command;
    Commands(String command){this.command=command;}
}
